### ISSUE TITLE
Any way to hide the user's Facebook profile etc

### ISSUE THREAD

**Issue by bryanc-nz** [danielbuechele/goofy#280] opened 2016-10-04 22:51 UTC
I have a new panel at the right side of the window showing the friends profile info and other details. It would be good if this panel could be hidden in order to reduce the screen footprint.

Thanks

**Comment by pkuczynski** [comment] 2016-10-05 08:42
This is a duplicate of #279. Check solution in #281

**Closed** 2016-10-05 10:30 UTC
