### ISSUE TITLE
Interface elemets overlaying

### ISSUE THREAD

**Issue by DotTheI** [danielbuechele/goofy#80] opened 2015-05-03 07:16 UTC
This is what can bee seen when the application window is narrowed

![2015-05-02 17 03 48](https://cloud.githubusercontent.com/assets/10737439/7444061/2267cfce-f17d-11e4-9606-11f918192dee.png)

**Comment by Sheraff** [comment] 2015-05-03 21:55
Duplicate of https://github.com/danielbuechele/goofy/issues/77

**Closed** 2015-05-04 08:47 UTC

**Comment by DotTheI** [comment] 2015-05-09 12:45
Thank you for fixing the issue!

PS I would like to translate the application into Russian

**Comment by danielbuechele** [comment] 2015-05-09 22:01
@DotTheI cool, enter your translations here: https://docs.google.com/spreadsheets/d/1ygCDE0GAG94pio2SLmTzn5rqSEWx84TAgCeBZEUXZFs/edit?usp=sharing

**Comment by DotTheI** [comment] 2015-05-10 09:00
@danielbuechele Done
