### ISSUE TITLE
Send image from file browser

### ISSUE THREAD

**Issue by kennysong** [danielbuechele/goofy#71] opened 2015-04-25 06:40 UTC
Currently, when you click the image button to send a picture, an overlay appears with the text "Drag and drop files into Goofy to attach them to your message". Is it possible instead to launch an open file prompt inside Goofy and choose the file from there? 

Messenger for Desktop seems to be able to accomplish this.
![screen shot 2015-04-25 at 2 37 39 pm](https://cloud.githubusercontent.com/assets/2199875/7331921/cf80c934-eb58-11e4-8750-d60148f7a23a.png)

This is also an annoyance because sometimes drag and drop will just stop functioning. Perhaps that should be a separate issue?

**Comment by danielbuechele** [comment] 2015-05-08 17:23
duplicate of #68

**Closed by danielbuechele** 2015-05-08 17:23 UTC
