### ISSUE TITLE
Can't open preferences

### ISSUE THREAD

**Issue by MekliCZ** [danielbuechele/goofy#348] opened 2017-03-15 23:15 UTC
When I click to Preferences in menu bar or I press CMD+, nothing happens. If there are no preferences, it would be nice to remove it from menu bar.

**Comment by leocaseiro** [comment] 2017-04-04 12:04
I can't reproduce that. I'm on mac os and if I click at preferences I can see the settings:

<img width="544" alt="screen shot 2017-04-04 at 10 04 04 pm" src="https://cloud.githubusercontent.com/assets/940070/24655713/adbbcf38-1982-11e7-9ba6-541b6026c6dc.png">

**Comment by leymannx** [comment] 2017-04-07 07:42
Confirming issue on freshly installed macOS Sierra.

**Comment by gslender** [comment] 2017-05-11 12:20
me too... no preferences open... any log file or how to see error messages so I can report something else? btw also on fresh sierra

**Comment by gslender** [comment] 2017-05-11 12:21
I closed the app and re-opened and now it does show preferences... so maybe this is a one time thing??

**Comment by danielbuechele** [comment] 2017-05-11 12:23
Which version of Gooy are you on? 3.2.1 is the latest.

**Comment by prosello** [comment] 2017-05-12 22:16
Upgrading from 3.2.0 to 3.2.1 fixed this issue for me.

**Comment by MekliCZ** [comment] 2017-05-12 22:18
I have updated to 3.2.1 and I still can't open preferences, so there isn't any change that fixes the issue in 3.2.1.

**Comment by leymannx** [comment] 2017-05-13 12:44
@MekliCZ Does completely closing and reopening fix the issue?

**Comment by AwaitingIrindul** [comment] 2017-12-14 12:35
The issue is still valid for version 3.2.2 on macOS High Sierra (10.13.2). 
I tried closing and reopening the app without success. I even rebooted but still no preferences.

**Comment by jklp** [comment] 2018-10-30 21:50
Created a pull request at #427 which should fix this

**Comment by jklp** [comment] 2018-11-08 21:34
Fixed in v3.3.2

**Closed** 2018-11-08 21:34 UTC
