### ISSUE TITLE
Conversations list not showing up

### ISSUE THREAD

**Issue by inicolas2** [danielbuechele/goofy#288] opened 2016-10-13 07:12 UTC
Hello, 

I'm using Goofy on macOS Sierra and I can't read the names of my contacts. 
![screen shot 2016-10-13 at 9 09 47 am](https://cloud.githubusercontent.com/assets/22809622/19339666/0df395ca-9125-11e6-9995-2229f872c9a5.png)

There is another bug when I log in, Facebook said it failed but when I clicked on the "Back" button, I have access to the Messenger Web App. 

I hope you will find the origin of the bug. 

Cordially, 

Nico

**Comment by jirizoudun** [comment] 2016-10-13 09:08
Hi,

I've issue with missing conversation names on MacOS El Captain too.

Jiri

**Comment by kittaakos** [comment] 2016-10-13 18:06
Duplicate of #285 (Goofy no longer displays chat names)

**Closed** 2016-10-14 09:15 UTC
