### ISSUE TITLE
Group chat titles with emoticons include the name of the emoticon

### ISSUE THREAD

**Issue by Tyilo** [danielbuechele/goofy#246] opened 2016-05-05 11:58 UTC
See: ![](https://a.pomf.cat/hzjjse.png)

**Comment by halflings** [comment] 2016-05-31 21:08
This is also true for notifications (they include the name of the emoticon), and is quite annoying!

**Comment by joallard** [comment] 2016-06-27 19:35
Looks like a regression of #137.

**Comment by danielbuechele** [comment] 2016-06-27 21:28
fixed in f709427

**Closed by danielbuechele** 2016-06-27 21:28 UTC
