### ISSUE TITLE
Desktop Notifications on Muted Conversations

### ISSUE THREAD

**Issue by mvd7793** [danielbuechele/goofy#244] opened 2016-04-29 17:40 UTC
Hello! Goofy is triggering desktop notifications on muted conversations. I confirmed that [messenger.com](http://messenger.com) does not do the same. :)

**Comment by iv597** [comment] 2016-05-09 22:15
Yep, this is definitely a thing. This should not be a thing.

If I have time at some point I may take a stab at making this no longer be a thing.

**Comment by iv597** [comment] 2016-05-09 22:20
Actually, this is a duplicate of #233

**Closed** 2016-05-09 22:21 UTC
