### ISSUE TITLE
TIP: Want notifications? Enable them via Messenger.com, instead of the app!

### ISSUE THREAD

**Issue by Vilscon** [danielbuechele/goofy#392] opened 2017-09-29 13:01 UTC
I quickly saw a few people having trouble enabling notifications. I'm not sure if your version is bugged or you simply didn't enable it correctly, but it's working here at least.

Please follow these easy steps to enable notifications:

1. Go to [Messenger.com](https://messenger.com)
1. Click on the cog wheel in the upper left corner
1. Click on 'Enable desktop notifications'
1. Click 'yes' at the pop-up that appears right now

==

I'm not sure whether you have to do the same thing, excluding the pop-up step, with the Goofy app as well, but.. Just do it in case :)

==

If it isn't working, feel free to reply here or create your own issue. This is just a simple tip/minor guide how I got it working. :) 

==

_I created this tip as an issue to have people see this when they want to create a new issue regarding the problem. Hopefully it helps._

**Comment by petr-ujezdsky** [comment] 2017-10-03 20:47
Good tip! I have used the Goofy's settings (`<cmd> + ,`) and checked the 'Enable desktop notifications' checkbox. Now it works!

**Comment by BenoitFreslon** [comment] 2017-10-10 13:26
Thanks! But now I got corner notifications when I send a message too.

**Comment by Vilscon** [comment] 2017-10-10 14:58
Hey @BenoitFreslon, that's odd and shouldn't happen. Restart Goofy and make sure you aren't talking to yourself :)

**Comment by BenoitFreslon** [comment] 2017-10-10 15:01
If I reboot goofy it's ok.
But that's weird, it's the second time.

**Comment by jklp** [comment] 2018-11-08 21:52
Close as duplicate of #336

**Closed by jklp** 2018-11-08 21:52 UTC
