### ISSUE TITLE
Crash when opening link

### ISSUE THREAD

**Issue by rcheetah** [danielbuechele/goofy#314] opened 2017-02-16 10:26 UTC
Everytime I open a link, the programm crashes. As simple as that.

OSX El Capitan (10.11.6)
iMac (Retina 5K, 27-inch, Late 2015)
Processor 3,2 GHz Intel Core i5
Graphic Card: AMD Radeon R9 M390 2048 MB

Goofy Version 2.2.6 (973)

**Comment by xxdavid** [comment] 2017-02-16 10:30
Duplicate of #311. Please search the issues before creating a new one.

**Comment by rcheetah** [comment] 2017-02-16 17:39
Sorry, my bad

**Comment by cadavre** [comment] 2017-02-24 07:16
Close issue then.

**Comment by joallard** [comment] 2017-02-27 16:47
Indeed, came here on a search, please close ;)

**Closed** 2017-02-28 00:13 UTC
