### ISSUE TITLE
Option to hide from Application Switcher

### ISSUE THREAD

**Issue by singalen** [danielbuechele/goofy#145] opened 2015-09-15 14:48 UTC
Any messenger is a distraction, so I'd love it to stay out of the way as much as possible.
Goofy shows up in Application Switcher on `Cmd-Tab` - I'd like it not to show up there.
I'd still love to see it in the dock and to see notifications.
Thanks!

**Comment by danielbuechele** [comment] 2015-09-19 10:37
duplicate of #67

**Closed by danielbuechele** 2015-09-19 10:37 UTC
