### ISSUE TITLE
conversation window

### ISSUE THREAD

**Issue by mbreyt** [danielbuechele/goofy#170] opened 2015-10-25 21:22 UTC
hi,

whenever I have a conversation open, the messages kinda jump up and down really quickly as if there were a formatting problem, like it's creating and deleting a new line really fast.

great work besides that, I'm really enjoying your app.

cheers,

Martin

**Comment by danielbuechele** [comment] 2015-10-26 08:55
duplicate of #165

**Closed by danielbuechele** 2015-10-26 08:55 UTC
