### ISSUE TITLE
Voice Message not play

### ISSUE THREAD

**Issue by maciekwyka** [danielbuechele/goofy#108] opened 2015-06-21 20:18 UTC
Voice Message is downloading instead playing.
![screen shot 2015-06-21 at 22 16 08](https://cloud.githubusercontent.com/assets/12991339/8273220/621c88d2-1863-11e5-8956-43ba03902b63.png)

**Comment by danielbuechele** [comment] 2015-07-07 03:33
duplicate of #89

**Closed by danielbuechele** 2015-07-07 03:33 UTC
