### ISSUE TITLE
Sound alert occurs when the first character is entered

### ISSUE THREAD

**Issue by Giltvedt** [danielbuechele/goofy#206] opened 2016-01-06 10:17 UTC
When I start to write a message in the conversation so I get sound alert. It occurs at the first sign entered. The same happens when selected text is overwritten with first character. And when after line break in new paragraph i same messages. Also with first character in new paragraph after line break.

On OS X, I have enabled "Flash the screen when an alert occurs" under Accessibility, Audio in System Preferences.

It's a bit annoying.

Edit: I'm still on OS X Yosemite (10.10.5) by some reason.

**Comment by jthomp** [comment] 2016-01-06 22:50
Have noted this issue, as well.

**Comment by danielbuechele** [comment] 2016-01-07 13:02
Yes, this is a problem everybody seems to have. We had this problem before, and tried to fix it using this function: https://github.com/danielbuechele/goofy/blob/master/server/src/fb.js#L279
But it looks like Facebook made some changes and this breaks again. I think the problem is that there is no `textarea` as long as the first character isn't typed.

**Comment by corbinschwartz** [comment] 2016-01-07 19:25
Can confirm this issue on 10.10.5 as well.

**Comment by jclusso** [comment] 2016-01-08 07:47
+1 on 10.11.2

**Comment by danielbuechele** [comment] 2016-01-08 22:23
should be fixed in v2.2.5

**Closed by danielbuechele** 2016-01-08 22:23 UTC

**Comment by jthomp** [comment] 2016-01-08 23:11
:+1: fixed for me. cheers!

**Comment by corbinschwartz** [comment] 2016-01-08 23:13
Works for me as well, thanks for the speedy fix!
