### ISSUE TITLE
Default to text input field when switching to app window

### ISSUE THREAD

**Issue by leetosc** [danielbuechele/goofy#339] opened 2017-03-06 18:43 UTC
It would be great if the app would be be ready to type in a message when switching to it (either by cmd+tab or clicking the icon).  Currently the easiest way to get to the text input after cmd+tabbing to the app is by clicking the message area.  It would be really nice to not have to use the mouse and be able to cmd+tab to the app, type a message, and switch back using only the keyboard.  This used to be the behavior before the v3 update.

**Comment by RvMouche** [comment] 2017-03-07 10:08
Duplicate of #322

**Closed** 2017-03-07 10:08 UTC
