### ISSUE TITLE
Text replacement

### ISSUE THREAD

**Issue by lamortheureuse** [danielbuechele/goofy#437] opened 2019-01-26 01:39 UTC
Please allow text substitution like it is mostly everywhere on Mac. In my opinion, I's an essential function of a chat application. 
Thank you:)

**Comment by jklp** [comment] 2019-02-11 20:49
Ugh I would love this too though unfortunately isn't supported in Electron (is also is missing in Slack, whatsapp, etc).

Will leave ticket open as I personally do want to fix this myself.  

As a workaround, I currently use aText for substitutions but I know they're other apps (TextExpander etc) which also do the job

**Comment by jklp** [comment] 2019-02-11 20:53
Oh it's duplicate of #333 so closing this issue.  Looks like there's a solution for #333 too so will hopefully be in v3.4.1

**Closed by jklp** 2019-02-11 20:53 UTC
Labels: enhancement
