### ISSUE TITLE
Field for writing messages is no longer automatically selected

### ISSUE THREAD

**Issue by Zvezke** [danielbuechele/goofy#365] opened 2017-04-06 09:50 UTC
I'm a keen user of keyboard shortcuts, and I usually use my keyboard to change between my applications. In previous versions of Goofy, whenever I'd select Goofy, the field for writing messages was automatically activated (i.e. the cursor was blinking – ready to write).
For some versions now, this hasn't been the case. So even though I select Goofy by keyboard, I still have to use the mouse/trackpad to press the field to activate it – I've tried pressing 'tab' hoping that would do, but no. Is it possible to reenable this function. I'd really appreciate it.

**Comment by Etheryte** [comment] 2017-04-06 13:48
Duplicate of https://github.com/danielbuechele/goofy/issues/322.

**Closed** 2017-04-14 13:24 UTC
