### ISSUE TITLE
Energy usage

### ISSUE THREAD

**Issue by marekgaj** [danielbuechele/goofy#351] opened 2017-03-17 13:18 UTC
Since the last update (version 3.1.0) I keep getting notifications about significant energy usage by the app. Also, sometimes when I type it freezes for a few moments with the loading mouse cursor.

![image](https://cloud.githubusercontent.com/assets/14923667/24044660/8455e1e8-0b1c-11e7-897c-cf11e845ff2a.png)

**Comment by bmpalmeida** [comment] 2017-03-24 07:40
I have exactly the same problem! I need to close it, in order to gain 1 or 2 hours of battery life.

**Comment by Etheryte** [comment] 2017-03-25 11:47
I did some preliminary testing on the issue using the [`top` command](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/top.1.html), namely:

```bash
top -stats command,power | grep "Electron  " --line-buffered >> power.log
```
Shortly, the above command allows us to monitor the unitless "power usage" (see [this article on the actual way the measurement is calculated](https://blog.mozilla.org/nnethercote/2015/08/26/what-does-the-os-x-activity-monitors-energy-impact-actually-measure/)) of the main Electron application. For simplicity's sake I've excluded the helper processes.

I ran three simple tests:
 * leaving the application on idle, but in the foreground;
 * hovering over different UI elements (contacts list and chat);
 * scrolling the views, both the contacts view and the chat view.

The results are as follows:

![Image graph of the measurement results.](http://i.imgur.com/wW8fzvd.png)

While this is knowingly a very quick and dirty test, I think it highlights the following points:
 * when the application is idle, the "power usage" is low;
 * the scrollable parts of the interface are the most taxing.

While both of those are intuitive, the extent of scrolling performance impact was a surprise to me. I don't have any proposals for improvements at the moment.

**Comment by rensa** [comment] 2017-03-29 03:44
I'm finding a massive increase in CPU usage that I think is probably related to animated GIF playback or display.

When I switch between one conversation with just text and emoji used recently (as in, as far back as is loaded by the view) and another that has a single animated GIF, there's a stark difference: from 1–2% for the app and its helper thread to 40–60%.

I'm not sure how feasible it is to implement something like only playing GIFs that are clicked on or only when the app is in focus, but maybe this would help control CPU and energy usage? Or maybe a more involved solution is required; I'm spitballing ;)

**Comment by Etheryte** [comment] 2017-03-29 07:20
In theory, the solution would be rather straight-forward: whenever there's an animated image, replace it with a static one and add a hover to show the animated one again.  
The problematic bit is knowing when to replace an animated image with a static replacement, currently there are no handlers bound to handle the internal loading and other logic.  
We may get away with something as simple as a [`web-request` filter](https://electron.atom.io/docs/api/web-request/) to notify us of when to check for images, but I haven't tested if it's a usable approach.  

All in all, I think it would be a good idea to include a prefpane option in the app for a _power saving mode_ or something along those lines: disable animations, certain hovers, hide animated images by default etc.

**Comment by mattmartincouk** [comment] 2017-05-03 08:43
I've been seeing poor battery performance on my Macbook Pro with Touchbar. Determined the cause was Goofy. 

With that running, I was topping out at about 4 hours. Without it running, i'm getting nearer the 9/10 hours expected on a single full charge.

**Comment by ericorr** [comment] 2017-09-11 18:19
Just want to confirm that in my experience animated GIFs cause a massive CPU usage when playing even if the app is out of focus. I usually just scroll up to a part of the conversation that doesn't have a GIF or delete the GIF.

**Comment by jklp** [comment] 2019-02-11 00:47
Hi, it appears that you're right - animated gifs on screen do cause high CPU usage though have noticed if the app is hidden (via cmd-h), on another desktop, or behind another window the CPU usage drops down to 0% (could be due to an upgrade in messenger.com / recent upgrade to Electron v4?)

Closing for now but please re-open if still occurring and will investigate

**Closed by jklp** 2019-02-11 00:47 UTC
Labels: bug
