### ISSUE TITLE
Make input field active on window activation

### ISSUE THREAD

**Issue by gklka** [danielbuechele/goofy#358] opened 2017-03-27 10:16 UTC
Feature request: When I click into the window anywhere, or open a hidden Goofy window by clicking its Dock icon, I think Goofy should focus the text field and enable me to type instantly.

**Comment by Etheryte** [comment] 2017-03-27 13:22
Duplicate of https://github.com/danielbuechele/goofy/issues/322.

**Closed** 2017-04-14 13:56 UTC
