### ISSUE TITLE
Display is very shaky as I type messages

### ISSUE THREAD

**Issue by mhaithaca** [danielbuechele/goofy#179] opened 2015-11-11 16:14 UTC
Hello, Daniel! Thanks for providing Goofy. I love having it as an option for my Facebook messages.

In the current version, 2.2.3 (I checked for updates and it says it's the latest), when I am typing in the "Type a message..." text field, either the text I'm typing and the icons to the right (the picture, smiley, cash, and thumbs up) jump as I hit each key, or sometimes the whole column of text of the message thread to date, above where I'm typing, jumps.

I have not spotted anywhere I can change the font or text size to see if it's a text rendering issue specific to the font.

If the above doesn't make sense, I can see if I can capture some screen video to share with you. Let me know!

Mark

**Comment by laimonasr** [comment] 2015-11-15 19:59
Hello. I have also encountered this issue. For me it shakes even when I am not typing anything and if I try typing the message while it is shaking then key inputs seem to lag a lot.

**Comment by sgwilym** [comment] 2015-11-16 09:15
Also have this problem, it makes having Goofy open somewhere an extremely distracting experience as the content flickers upwards by about 20 pixels intermittently.

**Comment by joallard** [comment] 2015-11-25 02:36
Possible duplicate of #165?

**Closed** 2017-02-28 00:14 UTC
Labels: v2
