### ISSUE TITLE
Uh oh...starting the app now just opens Messenger.com in Safari.

### ISSUE THREAD

**Issue by ialexryan** [danielbuechele/goofy#56] opened 2015-04-15 05:15 UTC
Reproduced on a friend's computer. Running 10.10.3. Opening the app simply opens Messenger.com in a new tab in Safari, and the app window remains blank with the loading spinner indefinitely.

**Comment by d4rky-pl** [comment] 2015-04-15 07:58
+1

**Comment by danielbuechele** [comment] 2015-04-15 08:13
Looks like Facebook recently changed something. However, I can not reproduce this bug. There is a list of URLs that are loaded inside of Goofy (https://github.com/danielbuechele/goofy/blob/master/Goofy/AppDelegate.swift#L156) and it looks like we need to add something here.

**Comment by leifniem** [comment] 2015-04-15 08:42
+1, redefining safari to "whatever is your default browser"

**Comment by danielbuechele** [comment] 2015-04-15 09:53
Should be fixed in 2.0.3

**Closed by danielbuechele** 2015-04-15 09:53 UTC
Labels: bug

**Comment by leifniem** [comment] 2015-04-15 09:57
confirmed. thanks Daniel :)

**Comment by bradfeehan** [comment] 2015-05-11 03:23
This is happening for me again with 2.1.1.

**Comment by ialexryan** [comment] 2015-05-11 03:35
Can't reproduce with 2.1.1. Try reinstalling the app?

**Comment by ialexryan** [comment] 2015-05-11 03:36
As a side note (having previously worked at Facebook) they do a ton of experiments where they test new code on randomly selected people. New code that might break Goofy, for example. So if it's broken for someone, that doesn't necessarily mean it will be broken for everyone (although it's a good indicator that it might be soon!)
