### ISSUE TITLE
Hide dock icon and add a menubar one?

### ISSUE THREAD

**Issue by Squash019** [danielbuechele/goofy#178] opened 2015-11-09 09:08 UTC
Hi!

Would it be possible to hide the dock icon and add an option to show a menubar one. It would come pretty handy, since I always use Goofy on the background and just show it when needed, so I don't find a real purpose for the icon "wasting" space on the dock.

Thank you for such a useful app!

**Comment by danielbuechele** [comment] 2015-11-09 10:19
duplicate of #67 
I hadn't any time to implement this yet. But I know this is a common feature request.

**Closed by danielbuechele** 2015-11-09 10:19 UTC
