### ISSUE TITLE
Side pain will no longer hide

### ISSUE THREAD

**Issue by allen121** [danielbuechele/goofy#281] opened 2016-10-05 00:17 UTC
Suddenly today, the side bar for all my messages will no longer hide when I press on the info icon in the upper right. I've tried uninstalling and reinstalling with no success. I'm using version 2.2.6 (973) on my MacBook Pro Retina running macOS Sierra (10.12 16A323).

**Comment by allen121** [comment] 2016-10-05 00:19
I was able to resolve it by going to messenger.com, hiding the pane there, quit Goofy, and reopen Goofy. Seems to me like some sort of API call is not working in the Goofy app.

**Comment by phodamentals** [comment] 2016-10-05 01:45
Thanks for the tip! Noticed this as well.

**Comment by pkuczynski** [comment] 2016-10-05 08:41
Have the same problem and above solution worked fine. Although its a bit annoying.

**Comment by pkuczynski** [comment] 2016-10-05 08:41
This is a duplicate of #279

**Closed** 2016-10-05 10:30 UTC
