### ISSUE TITLE
Failure when opening any link

### ISSUE THREAD

**Issue by maziman84** [danielbuechele/goofy#312] opened 2017-02-11 08:45 UTC
Version 2.2.6 (973)
Any link lead to failed Goofy.

**Comment by eliduke** [comment] 2017-02-13 18:48
Yep. This is happening for me too.

**Comment by xxdavid** [comment] 2017-02-13 19:30
Duplicate of #311. Please search the issues before creating a new one.

**Closed** 2017-02-28 00:13 UTC
