### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by monon0ke** [danielbuechele/goofy#181] opened 2015-11-12 04:10 UTC
Basically my app no longer sends me notifications. It's no longer in my notification centre. I have redownloaded and logged out and even restarted my computer but nothing is working. Please help me it's really infuriating

**Comment by danielbuechele** [comment] 2015-11-12 09:06
Is it enabled in the notification settings in system preferences?

**Comment by freinbichler** [comment] 2015-11-12 09:17
I am having the same problem, Goofy does not send notifications anymore. It only makes the sound and updates the badge icon when I receive new messages. Seems to be a general problem.

**Comment by danielbuechele** [comment] 2015-11-25 09:38
Ok, this seems to be a problem for everyone. Fixes welcome.

**Comment by danielbuechele** [comment] 2015-11-26 13:12
fixed in latest release

**Closed by danielbuechele** 2015-11-26 13:12 UTC

**Comment by redvex** [comment] 2015-11-26 13:41
Just updated… Preference doesn’t show up now

**Comment by danielbuechele** [comment] 2015-11-26 13:55
duplicate of #188
