### ISSUE TITLE
Unable to add photos

### ISSUE THREAD

**Issue by ericweir** [danielbuechele/goofy#402] opened 2018-02-13 13:23 UTC
Yesterday you responded to a query from me about adding photos to messages in Goofy. You said it does work. 

It's not working for me. All the buttons except the add-a-photo button work. I'm on a MacBook running High Sierra. My only browser is Safari.

Thanks,

Eric Weir
eeweir@bellsouth.net

**Comment by jklp** [comment] 2018-11-08 21:21
Close as duplicate of #399

**Closed by jklp** 2018-11-08 21:21 UTC
