### ISSUE TITLE
Typing slows down requiring restart

### ISSUE THREAD

**Issue by sambostock** [danielbuechele/goofy#154] opened 2015-10-02 15:17 UTC
After a while, typing slows down to a crawl.  Eventually, there is a time gap between when each character typed shows up on the screen.  Once Goofy goes full typewriter, the only way to fix it seems to be to close and reopen the app, and wait until next time it does it.

**Comment by sgwilym** [comment] 2015-10-17 11:47
I'm also having this problem, and this seems to be a (better titled) duplicate of #149.

**Comment by raine** [comment] 2015-11-20 14:04
Seeing this.

**Closed** 2017-02-28 00:14 UTC
Labels: v2
