### ISSUE TITLE
Bigger text

### ISSUE THREAD

**Issue by melvinwalker** [danielbuechele/goofy#219] opened 2016-01-30 22:33 UTC
I'm older and my eyesight is starting to go. I would appreciate the ability to increase the text size in goofy.

Frankly, that's the only thing I can think of to change! Keep up the good work (and make the font bigger!).

**Comment by danielbuechele** [comment] 2016-01-31 14:42
duplicate of #34

**Closed by danielbuechele** 2016-01-31 14:42 UTC
