### ISSUE TITLE
Application doesn't reopen in same place and size

### ISSUE THREAD

**Issue by bmpalmeida** [danielbuechele/goofy#356] opened 2017-03-24 09:19 UTC
In Version 3.1.0, when i reopen the application it goes in the center of the screen.

It doesn't resize and position to the place of the last session.

**Comment by Etheryte** [comment] 2017-03-28 17:39
Duplicate of https://github.com/danielbuechele/goofy/issues/323.

**Closed** 2017-04-14 13:56 UTC
