### ISSUE TITLE
Contactlist blank

### ISSUE THREAD

**Issue by tigersoul925** [danielbuechele/goofy#286] opened 2016-10-12 15:35 UTC
The contactlist is now blank. Just the avatars are showing. See screenshot.
![screen shot 2016-10-12 at 17 33 27](https://cloud.githubusercontent.com/assets/14020174/19316562/3bbaefea-90a2-11e6-8541-d1797d2f791d.png)

**Comment by kittaakos** [comment] 2016-10-13 18:06
Duplicate of [Goofy no longer displays chat names].

[Goofy no longer displays chat names]: https://github.com/danielbuechele/goofy/issues/285

**Comment by tigersoul925** [comment] 2016-10-13 18:09
Ah ,sorry, didn't find that one!

**Closed** 2016-10-14 09:15 UTC
