### ISSUE TITLE
Crashes on boot

### ISSUE THREAD

**Issue by PiwwowPants** [danielbuechele/goofy#115] opened 2015-07-11 16:25 UTC
When you have Goofy set to open at startup and you log in for the first time from a boot, it crashes immediately. It attempts to load a while until you hit CMD+R, then it crashes and restarts.

Issue exists on Yosemite and El Capitan.

**Comment by andremiguelaa** [comment] 2015-07-11 16:41
Same problem here with OSX Yosemite.

**Comment by danielbuechele** [comment] 2015-07-14 00:53
duplicate of #114

**Closed by danielbuechele** 2015-07-14 00:53 UTC
