### ISSUE TITLE
Cant see message while writing it

### ISSUE THREAD

**Issue by iBobik** [danielbuechele/goofy#103] opened 2015-06-12 10:02 UTC
At this video I wrote message, but we can not see cursor and written text except of first character. Also when clicking to middle of text it will not write there, but at the end.

https://www.dropbox.com/s/ejiyct5fnovk69m/Goofy%20bug.mov?dl=0

**Comment by hashier** [comment] 2015-06-13 07:58
Duplicate of #99 and it's fixed. Was a bug on Facebook's side.

**Closed** 2015-06-13 14:07 UTC
