### ISSUE TITLE
How to active notifications Sound + Corner messages

### ISSUE THREAD

**Issue by BenoitFreslon** [danielbuechele/goofy#391] opened 2017-09-27 21:42 UTC
Hello, I installed the 3.2.2 version on OS X 10.12.6

But i don't see any notifications or sounds.
Just badges on the icon in the dock.

Thanks

**Comment by petr-ujezdsky** [comment] 2017-09-28 17:48
I have the sound, but no notifications at all.
Goofy 3.2.2, macOS Sierra 10.12.6

**Comment by Vilscon** [comment] 2017-10-03 10:42
See my latest post @ issues, which isn't an issue, but a guide actually. :)

**Comment by jklp** [comment] 2018-11-08 21:51
Close as duplicate of #392 and #396.

**Closed by jklp** 2018-11-08 21:51 UTC
