### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by RvMouche** [danielbuechele/goofy#336] opened 2017-03-03 20:44 UTC
Wasn't sure until now, but notifications don't show on my mac (2014 rmbp 15", Sierra). The sound is made though and notifications from other apps come through.

**Comment by CoWinkKeyDinkInc** [comment] 2017-03-04 03:56
On Macbook Pro 2010 on Sierra, this problem also occurs to me.

**Comment by Boncio22** [comment] 2017-03-04 11:31
Same here on Macbook Pro 2012 (non-retina) on Sierra 10.12.4 Beta.
Sometimes closing app with command + Q and reopening solves problem for about 15 minutes

**Comment by danielbuechele** [comment] 2017-03-04 14:36
I heard that from several people, but can't reproduce. Seems like Facebook is A/B-testing something there. Would be great if someone having this issue can help debugging.

**Comment by Boncio22** [comment] 2017-03-04 14:40
I observed now that this occurs after closing some fullscreen apps e.g. atom.
Also when I have notifications I can't click on them to open goofy

**Comment by RvMouche** [comment] 2017-03-04 18:03
@danielbuechele tell me what you need! I'd like to help debugging

**Comment by danielbuechele** [comment] 2017-03-05 00:25
What I need, is a scenario to reliable reproduce this behavior and all steps that happen in this scenario.

**Comment by RvMouche** [comment] 2017-03-07 10:07
Alright, I'll be one the lookout to see if I can get a scenario in which the notifications *do* work, so I can make one where they don't.

**Comment by CoWinkKeyDinkInc** [comment] 2017-03-09 02:25
The notifications are working properly for me now all of a sudden.  Although the red circle does not go greater than 1, even when the same person sends multiple messages.

**Comment by danielbuechele** [comment] 2017-03-12 23:20
Version 3.1.0 implements notification a little different. Let me know if the problem still exists.

**Comment by duongdev** [comment] 2017-06-11 20:00
Notification doesn't work all the time for me. Seems like Facebook runs several versions of Messenger in other countries and the element classes are different in each version.
I am running 3.2.1 on my Sierra from Vietnam.

**Comment by danielbuechele** [comment] 2017-06-12 07:56
This problem has returned. Facebook changed their code. PRs welcome.

**Comment by jklp** [comment] 2018-11-21 10:31
The reason for this was that previously, Notifications were created by Goofy when it detected that the DOM had changed a new message was created.  What it does now is hijack the Web Notification that Facebook sends, does some slight tweaks to make it native, and then present that Notification to the user - hopefully this will be more reliable than previously 🤞 

Fixed in 3.3.4

**Closed by jklp** 2018-11-21 10:31 UTC
Labels: bug
