### ISSUE TITLE
Settings / Gear Symbol - Not working on side conversation bar, nor on individual settings button within conversation.

### ISSUE THREAD

**Issue by jakezee** [danielbuechele/goofy#368] opened 2017-04-18 15:38 UTC
Been like this for months now more or less. Clicking on it in the multiple conversation pane does nothing, clicking on it in the conversation - after info - produces the following:

<img width="1558" alt="screenshot 2017-04-18 17 35 53" src="https://cloud.githubusercontent.com/assets/27733210/25139485/ade2cb48-245d-11e7-828a-a2069c2e248e.png">

**Comment by Etheryte** [comment] 2017-04-20 00:11
Duplicate of https://github.com/danielbuechele/goofy/issues/346.

**Closed** 2017-04-20 07:50 UTC
