### ISSUE TITLE
Can't send images

### ISSUE THREAD

**Issue by toph-allen** [danielbuechele/goofy#43] opened 2015-04-10 19:58 UTC
The image button seems to be missing for me. No other info that I can think of—I've tried removing preference files etc.

![screen shot 2015-04-10 at 3 57 53 pm](https://cloud.githubusercontent.com/assets/3117884/7095689/669371ca-df9a-11e4-98af-ffb92374b90a.png)

**Comment by danielbuechele** [comment] 2015-04-11 08:55
duplicate of #30

**Closed by danielbuechele** 2015-04-11 08:55 UTC
